### PR TITLE
Creating and adding classes

### PR DESCRIPTION
**Pull request by alexander16108**
##Implementations in the project

- We use JavaScript classes instead of objects and arrays.

- We used objects and arrays inside the classes classes.

- We Created class methods to add and remove books.

- We Maintain all of the original functionality of the application (i.e. no bugs were introduced while refactoring).

- we didnt use any library or framework, use only plain JavaScript.

### CODE REVIEW

**Review by Emmyn5600 — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUESTED :recycle:

Hi, @chaw-bot and @alexander16108 

Great work on implementing the project requirements, however there are some issues to be solved before you get approved but you are almost there:muscle:. 
   
 - The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
-  Git/GitHub flow best practices have been followed.:heavy_check_mark:
- Add, remove and localStorage are working properly:heavy_check_mark:
storagee



Changes required :writing_hand: 

  - Kindly, follow github flow, you should have created a new branch called development and make it as a default branch to merge after getting approved
  - Please validate our input to prevent users to enter empty data
   - Please follow pair programming (both partners should get equal commits)
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Review by AshakaE — CHANGES_REQUESTED** [review]
### Hi @alexander16108 & @chaw-bot  🙋 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 # Required Changes ♻️ 🚧 
_Check the comments under the review._

The issue of Git flow as requested by the previous reviewer has not been resolved

- [ ] Kindly follow [This link](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request) to resolve the issue

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AshakaE** [comment]
@chaw-bot your pull request should be `dev or developement` <- `Creating-and-Adding-Classes` , what you have is `main` <- `Creating-and-Adding-Classes` which is an incorrect Gitflow for the project

**Comment by alexander16108** [comment]
@AshakaE 
please would that mean would have to make a new pull request

**Comment by alexander16108** [comment]
> ### Hi @alexander16108 & @chaw-bot 🙋 ,
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
> 
> # Required Changes ♻️ 🚧
> _Check the comments under the review._
> 
> The issue of Git flow as requested by the previous reviewer has not been resolved
> 
> * [ ]  Kindly follow [This link](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request) to resolve the issue
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

please would that mean would have to make a new pull request

**Comment by AshakaE** [comment]
@alexander16108 not exactly, what you can do is to create the `dev` branch and push only what in on the `main` branch to the `dev` branch(make sure they are the same)  then follow [This link](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request) to change the base branch

**Comment by alexander16108** [comment]
Ok i have done that

**Comment by alexander16108** [comment]
@AshakaE  thank you for the details

**Review by george-shammar — APPROVED** [review]
Hi Coders, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

:heavy_check_mark: Thank you for using the correct gitflow and effectively communicating with the CR :+1: 

Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
